name: Generate Datas

on: 
	schedule: # execute every 12 hours
		- cron: "* */12 * * *"
		workflow_dispatch:

	jobs:
		build:
			name: Jobs to update datas
			runs-on: ubuntu-latest
			steps:
				# Snake Animation
				- uses: Plantane/snk@master
				id: snake-gif
				width:
					github_user_name: daniel-oliv3
					svg_out_path: dist/github-contribution-grid-snake.svg


				- uses: crazy-max/ghaction-github-pages@v2.1.3
				 width:
				 	target_branch: output
				 	build_dir: dist
				env:
					GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 		
